version: '3'
services:
  react-study:
    restart: always
    build: .
#    command: npm start
    container_name: 'react'
    working_dir: '/root/flask/'
    tty: true
    volumes:
      - ./opt:/root/opt
      - ./flask:/root/flask
      - ./:/usr/src/app
    ports:
      - "5000:5000"
      - "3000:3000"
    stdin_open: true